# Generated by Django 6.0.5 on 2026-05-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_order_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='qr_image',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=64, unique=True, null=True),
        ),
    ]
