# Generated by Django 6.0.5 on 2026-05-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='events/'),
        ),
    ]
