# Generated by Django 6.0.5 on 2026-06-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(default='Check-in Staff', max_length=100),
        ),
    ]
