# Generated by Django 6.0.5 on 2026-06-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
