# Generated by Django 6.0.5 on 2026-06-09 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_passwordresetotp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='singer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.singer'),
        ),
    ]
