# Generated by Django 6.0.5 on 2026-06-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_event_external_url_event_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='event',
            name='ticketing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged per ticket', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time fee charged during checkout', max_digits=10),
        ),
    ]
