# Generated by Django 6.0.5 on 2026-06-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_remove_event_platform_fee_event_ticketing_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='transaction_fee',
        ),
        migrations.AddField(
            model_name='event',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticketing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
